site_name: Plugin Development
#theme: bootstrap
theme: readthedocs
pages:
- [index.md, Home]
- ['user-guide/overview.md', 'Topics', 'Overview']
- ['user-guide/getting-started.md', 'Topics', 'Getting Started']
- ['user-guide/protocol.md', 'Topics', 'Protocol']
- ['user-guide/metrics.md', 'Topics', 'Metrics']
- ['user-guide/manifest.md', 'Topics', 'Manifest']
- ['user-guide/parameters.md', 'Topics', 'Parameters']
- ['user-guide/testing.md', 'Topics', 'Testing']
- ['user-guide/documentation.md', 'Topics', 'Documentation']
- ['user-guide/checklist.md', 'Topics', 'Checklist']
- ['user-guide/tools.md', 'Topics', 'Tools']
